---
    parserOptions:
        ecmaFeatures:
            jsx: true
    plugins:
        - react
        - import
    settings:
        'import/ignore':
        # We don't want to lint some modules/files
        - vendor
        - flux
        - package.json
        - ../shared/errors.json
        - lodash.throttle
        - react
        - react-dom
    globals:
        "$": true
    rules:
        # Parent rules that are overriden.

        # Conflicts with another React rule forcing several lines tags to be
        # withing parenthesis.
        no-extra-parens:
            - 0
        # Can't enforce when enforcing a functions ordering.
        no-use-before-define:
            - 0

        # React plugin rules.
        react/display-name:
            - 0
        react/forbid-component-props:
            - 0
        react/forbid-prop-types:
            - 2
            - {'forbid': ['any']}
        react/no-children-prop:
            - 2
        react/no-danger:
            - 2
        react/no-danger-with-children:
            - 2
        react/no-deprecated:
            - 2
        react/no-did-mount-set-state:
            - 2
        react/no-did-update-set-state:
            - 2
        react/no-direct-mutation-state:
            - 2
        react/no-find-dom-node:
            - 2
        react/no-is-mounted:
            - 2
        react/no-multi-comp:
            - 0
        react/no-render-return-value:
            - 2
        react/no-set-state:
            - 0
        react/no-string-refs:
            - 1 # TODO 2
        react/no-unescaped-entities:
            - 2
        react/no-unknown-property:
            - 2
        react/no-unused-prop-types:
            - 2
        react/prefer-es6-class:
            - 2
        react/prefer-stateless-function:
            - 2
        react/prop-types:
            - 1 # TODO 2
        react/react-in-jsx-scope:
            - 2
        react/require-optimization:
            - 0
        react/require-render-return:
            - 2
        react/self-closing-comp:
            - 2
        react/sort-comp:
            - 0
        react/sort-prop-types:
            - 0
        react/style-prop-object:
            - 2

        # JSX specific rules.
        # Enforce boolean attributes notation in JSX
        react/jsx-boolean-value:
            - 2
            - 'always'
        react/jsx-closing-bracket-location:
            - 2
            - { selfClosing: 'line-aligned', nonEmpty: 'after-props' }
        react/jsx-curly-spacing:
            - 2
            - 'always'
        react/jsx-equals-spacing:
            - 2
        react/jsx-filename-extension:
            - 0
        react/jsx-first-prop-new-line:
            - 2
            - "multiline-multiprop"
        react/jsx-handler-names:
            - 2
        react/jsx-indent:
            - 2
            - 4
        react/jsx-indent-props:
            - 2
            - 2
        react/jsx-key:
            - 2
        react/jsx-max-props-per-line:
            - 2
            - { 'maximum': 1 }
        react/jsx-no-bind:
            - 2
        react/jsx-no-comment-textnodes:
            - 2
        react/jsx-no-duplicate-props:
            - 2
        react/jsx-no-literals:
            - 0
        react/jsx-no-target-blank:
            - 2
        react/jsx-no-undef:
            - 2
        react/jsx-pascal-case:
            - 2
        react/jsx-sort-props:
            - 0 # lolno
        react/jsx-space-before-closing:
            - 2
            - "always"
        #react/jsx-tag-spacing:
        #    - 2
        #    - { closingSlash: "never", beforeSelfClosing: "always", afterOpening: "never" }
        react/jsx-uses-react:
            - 2
        react/jsx-uses-vars:
            - 2
        react/jsx-wrap-multilines:
            - 2

        # Import rules. TODO to be hoisted?
        import/no-unresolved:
            - 2
        import/named:
            - 2
        import/default:
            - 0
        import/namespace:
            - 2
        import/no-restricted-paths:
            - 0
        import/no-absolute-path:
            - 2
        import/no-dynamic-require:
            - 2
        import/no-internal-modules:
            - 0
        import/no-webpack-loader-syntax:
            - 0 # we don't use webpack

        import/export:
            - 2
        import/no-named-as-default:
            - 2
        import/no-named-as-default-member:
            - 2
        import/no-deprecated:
            - 2
        import/no-extraneous-dependencies:
            - 0
        import/no-mutable-exports:
            - 2

        import/unambiguous:
            - 2
        import/no-commonjs:
            - 0
        import/no-amd:
            - 0
        import/no-nodejs-modules:
            - 0

        import/first:
            - 0
        import/no-duplicates:
            - 2
        import/no-namespace:
            - 0
        import/extensions:
            - 0
        import/order:
            - 0
        import/newline-after-import:
            - 2
        import/prefer-default-export:
            - 0
        import/max-dependencies:
            - 0
        import/no-unassigned-import:
            - 2
        import/no-named-default:
            - 2
