# Note: We use --silent argument on npm invocations to keep the output simple
# and readable through email notifications.
image: node:4.4.4-slim

before_script:
    - apt-get update -qq && apt-get install -y -qq libpng-dev
    - npm install --silent

stages:
    - lint
    - build
    - test

lint:
    stage: lint
    script:
        # Lint JS code
        - npm run --silent lint-full
        # And check banks and locales are correct
        - npm run --silent check

build:
    stage: build
    script:
        # Check everything builds correctly
        - npm run --silent build

test:
    stage: test
    script:
        # Run the UI test suite
        - npm run --silent test
