# Note: We use --silent argument on npm invocations to keep the output simple
# and readable through email notifications.
image: node:6

before_script:
    - yarn install

cache:
    key: 'node-modules-kresus'
    paths:
        - node_modules/
        - yarn.lock

stages:
    - lint
    - build
    - test

lint:
    stage: lint
    script:
        # Lint JS code
        - npm run --silent lint-full
        # And check banks and locales are correct
        - npm run --silent check

build:
    stage: build
    script:
        # Check everything builds correctly
        - npm run --silent build-no-progress
    cache:
        policy: pull

test:
    stage: test
    script:
        # Run the UI test suite
        - npm run --silent test
    cache:
        policy: pull

npm:
    stage: test
    cache:
        key: "npm"
    script:
        # Try to build with NPM
        - npm install --silent
        - npm run --silent build-no-progress
